[18.0][MIG] l10n_eu_product_adr
chaule97/community-data-files pull request #1
Opened 2024-09-26 03:46 UTC by chaule97

- I removed the test case `test_06_product_variant_migration` because there is no more pre-migration in Odoo 16+.
- I need to update the `name_search` method in `AdrClass` and `AdrGoods` because the `name_search` method in Odoo 18 has changed and no longer searches by name.

2024-09-26 07:27 UTC, QuocDuong1306 requested changes
As discussed, could you double-check

2024-09-26 07:27 UTC, QuocDuong1306 commented on l10n_eu_product_adr/__manifest__.py
> +    "version": "18.1.0.0.0",
could you fix?

2024-09-26 07:27 UTC, QuocDuong1306 commented on l10n_eu_product_adr/models/adr_class.py
> +            )
Could you double check for this one?

As I know, since 17.0, Odoo have taken into account the `display_name` instead of `name_get` ([16.0](https://github.com/odoo/odoo/blob/096319e18039a677a2e2b09021198979adddc156/odoo/models.py#L1623)) to the `name_search` ([here](https://github.com/odoo/odoo/blob/7f2148253065b7cb9d3ae21cca89ace87abfb883/odoo/models.py#L1755))

So could you take a chance to apply some new improvements for them?

2024-09-26 07:27 UTC, QuocDuong1306 commented on l10n_eu_product_adr/models/adr_goods.py
> +            )
same idea with above

2024-09-26 07:27 UTC, QuocDuong1306 commented on l10n_eu_product_adr/views/product_template_views.xml
> +                    invisible="type != 'product' or (not is_dangerous and not adr_goods_on_variants)"
Could you double check those forms, I can't see the Dangerous page

![image](https://github.com/user-attachments/assets/1e38facf-edb2-466c-a948-575670e972e1)

2024-09-26 09:23 UTC, chaule97 commented on l10n_eu_product_adr/views/product_template_views.xml
> +                    invisible="type != 'product' or (not is_dangerous and not adr_goods_on_variants)"
Thanks, I just discovered that Odoo 18 have updated use [is_storable](https://github.com/odoo/odoo/blob/0f69fba3148a476224d15fa9349f88f63bb1a4ed/addons/stock/models/product.py#L666) instead of `type='product'`

2024-09-27 03:23 UTC, QuocDuong1306 requested changes
Thanks

IMO, all the `data` files can be marked as nopupdated

And I think we should write a little bit in PR's description about the failing tests when running Odoo with enterprise version

```
2024-09-27 02:43:09,369 35855 INFO l10n_eu_product_adr_2 odoo.tests.suite: ====================================================================== 
2024-09-27 02:43:09,369 35855 ERROR l10n_eu_product_adr_2 odoo.tests.suite: ERROR: setUpClass (odoo.addons.l10n_eu_product_adr.tests.test_adr_points.TestAdrPoints)
Traceback (most recent call last):
  File "/home/quocduong/code/odoo/project_18/community-data-files/l10n_eu_product_adr/tests/test_adr_points.py", line 11, in setUpClass
    super().setUpClass()
  File "/home/quocduong/code/odoo/odoo/18.0/addons/stock/tests/common.py", line 148, in setUpClass
    cls.warehouse_1 = cls.env['stock.warehouse'].create({
  File "<decorator-gen-94>", line 2, in create
  File "/home/quocduong/code/odoo/odoo/18.0/odoo/api.py", line 479, in _model_create_multi
    return create(self, [arg])
  File "/home/quocduong/code/odoo/odoo/18.0/addons/stock/models/stock_warehouse.py", line 142, in create
    new_vals = warehouse._create_or_update_sequences_and_picking_types()
  File "/home/quocduong/code/odoo/odoo/18.0/addons/stock/models/stock_warehouse.py", line 387, in _create_or_update_sequences_and_picking_types
    warehouse_data[picking_type] = PickingType.create(values).id
  File "<decorator-gen-91>", line 2, in create
  File "/home/quocduong/code/odoo/odoo/18.0/odoo/api.py", line 479, in _model_create_multi
    return create(self, [arg])
  File "/home/quocduong/code/odoo/odoo/18.0/addons/stock/models/stock_picking.py", line 170, in create
    return super().create(vals_list)
  File "<decorator-gen-0>", line 2, in create
  File "/home/quocduong/code/odoo/odoo/18.0/odoo/api.py", line 480, in _model_create_multi
    return create(self, arg)
  File "/home/quocduong/code/odoo/odoo/18.0/odoo/models.py", line 4893, in create
    records = self._create(data_list)
  File "/home/quocduong/code/odoo/odoo/18.0/odoo/models.py", line 5077, in _create
    cr.execute(SQL(
  File "/home/quocduong/code/odoo/odoo/18.0/odoo/sql_db.py", line 354, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: null value in column "restrict_put_in_pack" of relation "stock_picking_type" violates not-null constraint
DETAIL:  Failing row contains (17, 0, 15, 24, 4, 35, null, 3, null, null, 1, 1, 1, IN, incoming, at_confirm, 2x7xprice, 4x12_lots, pdf, BWHIN, ask, direct, {"en_US": "Receipts"}, null, null, t, t, f, null, f, null, null, null, null, null, null, null, null, null, 2024-09-27 02:43:08.616485, 2024-09-27 02:43:08.616485, null, null, null, null, null, null, null, null, null, null).
```

2024-09-27 03:23 UTC, QuocDuong1306 commented on l10n_eu_product_adr/models/adr_goods.py
> +                )
```suggestion
                affixes.append(
                    _("qty:%(limited_quantity)s %(limited_quantity_uom_id)s,
                        limited_quantity=rec.limited_quantity,
                        limited_quantity_uom_id=rec.limited_quantity_uom_id.name,
                    )
                )
```
`format` structure is deprecated, we can use `%(xxx)s` instead

2024-09-27 03:23 UTC, QuocDuong1306 commented on l10n_eu_product_adr/models/adr_label.py
> +                )
same with above

2024-09-27 03:55 UTC, chaule97 commented
Hi @QuocDuong1306 , I have updated all of code and PR description

2024-09-27 04:34 UTC, QuocDuong1306 approved these changes

2024-09-27 05:31 UTC, QuocDuong1306 commented
According to the suggestion from Nils, we can add this one to fix the issue
```
from odoo.tests import Form, tagged
@tagged('post_install', '-at_install')
```

2024-10-08 05:25 UTC, xaviedoanhduy commented on l10n_eu_product_adr/views/product_product_views.xml
> +                <attribute name="attrs" />
> the "attrs" and "states" attributes are no longer used.

2024-10-08 05:26 UTC, xaviedoanhduy commented
@chaule97, could u have a look at product variant form view?
![image](https://github.com/user-attachments/assets/1e5c6e6b-a851-456b-8932-44c4bd5cb748)

2024-10-08 08:59 UTC, xaviedoanhduy approved these changes

2024-10-09 04:25 UTC, closed without merging